### ISSUE TITLE
how do i access and display the created html?

### ISSUE THREAD

**Issue by albrecmi** [bumaas/HMInventory#3]
hello, sry for the beginner question, 
i left the default value: "/var/lib/symcon/HM_inventory.html".
so how do i access and display the created html?
- in webfront?
- in managment console?

thanks

**Comment by bumaas** [comment]
Could you please use the Symcon Forum (https://community.symcon.de/t/modul-hminventory/46930) for questions?

Burkhard

**Comment by bumaas** [comment]
Closed
